PSW-Library-2025/library/catalog/urls.py
from django.urls import path
from . import views

urlpatterns = [ path('' , views.index, name='index'),
                path('books/' , views.BookListView.as_view() , name='books' ),
                path('authors/', views.AuthorListView.as_view(), name='authors'),
                path('book/<int:pk>',views.BookDetailView.as_view(),name='book-detail'),
                path('author/<int:pk>',views.AuthorDetailView.as_view(),name='author-detail') ,
                path('resetlogin/<path:next>', views.resetlogin, name='resetlogin') ,
                path('loaned_books/', views.AllLoanedBooksListView.as_view(), name='all-loaned-books'),
                path('book/<uuid:pk>/renew/', views.renew_book_librarian,name='renew-book-librarian') ,
                path('signup/<path:next>', views.user_signup, name='signup'),
                path('search_book_librarian', views.search_book_librarian, name='search-book-librarian'),
                path('set_book_on_maintenance/<uuid:pk>',views.set_book_on_maintenance,name='set-book-on-maintenance')  ]

PSW-Library-2025/library/library/urls.py
from django.contrib import admin
from django.urls import path


urlpatterns = [
    path("admin/", admin.site.urls),
]

from django.urls import include
urlpatterns += [path('catalog/', include('catalog.urls')),]

from django.views.generic import RedirectView
urlpatterns += [ path('', RedirectView.as_view(url='catalog/')),]

from django.conf import settings
from django.conf.urls.static import static
urlpatterns+= static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns+= [ path('accounts/', include('django.contrib.auth.urls')), ]

PSW-Library-2025/library/catalog/models.py
from django.db import models

# Create your models here.

from django.urls import reverse

class Genre(models.Model):
    name = models.CharField(max_length=200, help_text="Enter a genre" )

    class Meta:
       ordering = ['name']

    def __str__(self):
       return self.name


class Language(models.Model):
    name = models.CharField(max_length=200, help_text="Enter language")

    class Meta:
        ordering = ['name']

    def __str__(self):
        return self.name

class Author(models.Model):
    first_name = models.CharField(max_length=100)
    last_name  = models.CharField(max_length=100)
    date_of_birth = models.DateField('Born', null=True, blank=True)
    date_of_death = models.DateField('Died', null=True, blank=True)

    class Meta:
        ordering = ['last_name', 'first_name']

    def get_absolute_url(self):
        return reverse('author-detail', args=[str(self.id)])

    def __str__(self):
        return f'{self.last_name}, {self.first_name}'
    

class Book(models.Model):
    title  = models.CharField(max_length = 200)
    author = models.ForeignKey(Author,
                null = True,
                on_delete = models.SET_NULL)
    summary = models.TextField(max_length = 1000,
                help_text = 'Describe the book')
    isbn    = models.CharField('ISBN', max_length = 13,
                unique = True, help_text = 'ISBN code')
    genre   = models.ForeignKey(Genre,
                                on_delete = models.SET_NULL,
                                null = True)
    language = models.ForeignKey(Language,
                                 on_delete = models.SET_NULL,
                                 null = True)

    def get_absolute_url(self):
        return reverse('book-detail', args=[str(self.id)])

    class Meta:
        ordering = ['title']

    def __str__(self):
        return self.title
 

import uuid
from datetime import date
from django.contrib.auth.models import User

class BookInstance(models.Model):
    id = models.UUIDField(primary_key = True,
                          default = uuid.uuid4,
                          help_text = "Unique ID for book")
    book = models.ForeignKey(Book, 
                             on_delete = models.RESTRICT,
                             null = True)
    imprint = models.CharField(max_length=200)
    due_back = models.DateField(null=True, blank=True)
    borrower = models.ForeignKey(User,
                                 on_delete = models.SET_NULL,
                                 null = True,
                                 blank = True)
    LOAN_STATUS = ( ('d', 'Maintenance'),
                    ('o', 'On loan'),
                    ('a', 'Available'),
                    ('r', 'Reserved'),)
    status = models.CharField(max_length = 1,
                              choices = LOAN_STATUS,
                              blank = True,
                              default = 'd',
                              help_text = 'Book availability')

    def is_overdue(self):
        return bool(self.due_back and (date.today() > self.due_back))

    class Meta:
        ordering = ['due_back', 'book']
        permissions = ( ("can_mark_returned", "Set book as returned"),)

    def __str__(self):
        return f'{self.id} ({self.book.title})'
    

PSW-Library-2025/library/catalog/forms.py
import datetime
from django import forms
from django.core.exceptions import ValidationError

class RenewBookForm(forms.Form):
    renewal_date = forms.DateField(help_text="Enter date.")

    def clean_renewal_date(self):
        data = self.cleaned_data['renewal_date']
        if data < datetime.date.today():
           raise ValidationError('Invalid - renewal in past')
        if data > (datetime.date.today() + datetime.timedelta(weeks=4)):
           raise ValidationError('Invalid date - too late')
        return data


from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['first_name','last_name','email','username', 'password1', 'password2']
        
class SearchBookTitleForm(forms.Form):
    title = forms.CharField( max_length = 100,
                             required = False,
                             help_text = "")
    
    def clean_title(self):
        data = self.cleaned_data['title']
        return data
    

PSW-Library-2025/library/catalog/views.py
from django.shortcuts import render

# Create your views here.
from .models import Book, Author

def index(request):
    n_books   = Book.objects.all().count()
    n_authors = Author.objects.all().count()
    num_visits = request.session.get('num_visits', 0)
    num_visits = num_visits + 1
    request.session['num_visits'] = num_visits
    request.session.modified = True
    ctx = {
             'num_books'    : n_books,
             'num_authors'  : n_authors,
             'num_visits'   : num_visits,
          }
    return render(request, 'index.html',context=ctx)


from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin

class BookListView(LoginRequiredMixin,generic.ListView):
    login_url = '/accounts/login/'
    model = Book
    paginate_by = 3
    
class AuthorListView(LoginRequiredMixin,generic.ListView):
    login_url = '/accounts/login/'
    model = Author
    paginate_by = 3
   
class BookDetailView(LoginRequiredMixin,generic.DetailView):
    login_url = '/accounts/login/'
    model = Book

class AuthorDetailView(LoginRequiredMixin,generic.DetailView):
    login_url = '/accounts/login/'
    model = Author

from django.http import HttpResponseRedirect
from django.urls import reverse

def resetlogin(request, next):
    request.session['num_visits'] = 0
    request.session.modified = True
    return HttpResponseRedirect(reverse('login') + "?next=" + next)
    
from .models import BookInstance
from django.contrib.auth.mixins import PermissionRequiredMixin

class AllLoanedBooksListView (LoginRequiredMixin,
                              PermissionRequiredMixin,
                              generic.ListView):
    login_url = '/accounts/login/'
    model = BookInstance
    permission_required = 'catalog.can_mark_returned'
    template_name = 'catalog/bookinstance_list_loaned.html'
    paginate_by = 3

    def get_queryset(self):
        all_l = BookInstance.objects.filter(status__exact='o')
        return all_l.order_by('due_back')


import datetime
from django.contrib.auth.decorators import login_required
from django.contrib.auth.decorators import permission_required
from django.shortcuts import get_object_or_404
from catalog.forms import RenewBookForm

@login_required
@permission_required('catalog.can_mark_returned', raise_exception = True)
def renew_book_librarian(request, pk):
    # Retrieve the book instance (or raise an error)
    book_instance = get_object_or_404(BookInstance, pk=pk)
    # If this is the first request (i.e. not a POST) then:
    # create the default form and render it
    if request.method != 'POST':
       p = datetime.date.today() + datetime.timedelta(weeks=3)
       form = RenewBookForm(initial={'renewal_date': p })
       ctx = { 'form': form, 'book_instance': book_instance }
       return render(request, 'catalog/book_renew_librarian.html', ctx)

    # ...otherwise...

    # ...this is a POST request,so:
    # - create a form instance and bind it with the POST data
    # - validate the form
    # - if the form is valid, process the data in cleaned_data
    #   and redirect to the page "exiting the form entry"
    # - if the form is not valid, re-render the page with errors

    form = RenewBookForm(request.POST)

    if form.is_valid():
       book_instance.due_back = form.cleaned_data['renewal_date']
       book_instance.save()
       return HttpResponseRedirect(reverse('all-loaned-books'))
    else:
       ctx = { 'form': form, 'book_instance': book_instance }
       return render(request, 'catalog/book_renew_librarian.html', ctx)


from django.contrib.auth import authenticate, login
from django.contrib.auth.models import Group
from .forms import SignupForm

def user_signup(request, next):
  if request.method != 'POST':
     form = SignupForm()
     return render(request, 'catalog/signup.html', {'form': form})
  else:
    form = SignupForm(request.POST)
    if form.is_valid():
       form.save()
       auth_user = authenticate(username=form.cleaned_data['username'],
                                password=form.cleaned_data['password1'])
       login(request, auth_user)
       gruppo_utenti = Group.objects.get(name='Utenti')
       auth_user.groups.add(gruppo_utenti)
       return HttpResponseRedirect(next)
    else:
       return render(request, 'catalog/signup.html', {'form': form})


from catalog.forms import SearchBookTitleForm

@login_required
@permission_required('catalog.can_mark_returned', raise_exception = True)
def search_book_librarian(request):
    # If this is the first request then:
    # create and render the default form.
    if request.method != 'POST':
       form = SearchBookTitleForm(initial={'title': ''})
       ctx = { 'form': form }
       return render(request, 'catalog/search_book_librarian.html', ctx)

    # otherwise...
    
    form = SearchBookTitleForm(request.POST)
    if form.is_valid(): # Form is valid: search, and render
       s = form.cleaned_data['title']
       #### Raw SQL formulation of query
       ###search_SQL = s + '%'
       ###found_books = Book.objects.raw( \
       ####       'SELECT * FROM catalog_book WHERE title LIKE %s', [search_SQL])

       ##### Equivalent filter-based formulation
       #####found_books = Book.objects.filter(title__startswith = s)    
       
       search_SQL = s.replace("*","%")
       found_books = Book.objects.raw( \
          'SELECT * FROM catalog_book WHERE title LIKE %s',
           [search_SQL])
       ctx = { 'search_title': s, 'found_books' : found_books }
       return render(request, 'catalog/searched_book_librarian.html', ctx)
    else:
       # Form is not valid: re-render it
       ctx = { 'form': form }
       return render(request, 'catalog/search_book_librarian.html', ctx)


from django.http import JsonResponse

def set_book_on_maintenance (request,pk):
    book_instance = get_object_or_404(BookInstance, pk=pk)
    book_instance.status = 'd'
    book_instance.save()
    return JsonResponse({'outcome' : 'OK',
                         'new_status': 'Maintenance',
                         'new_style' : 'text-warning',
                         'new_button': ''})

PSW-Library-2025/library/catalog/templates/catalog/author_detail.html
{% extends "base_generic.html" %}

{% block content %}
   <h1>Author: {{ author.first_name }} {{ author.last_name }}</h1>
   <p><strong> Name: </strong> {{ author.first_name }}</p>
   <p><strong> Surname: </strong> {{ author.last_name }}</p>
   <p><strong> Birth date:</strong> {{ author.date_of_birth }}</p>
   <p><strong> Death date:</strong> {{ author.date_of_death }}</p>
{% endblock %}

PSW-Library-2025/library/catalog/templates/catalog/author_list.html
{% extends "base_generic.html" %}
  
{% block content %}
   <h1>Author List</h1>
   {% if author_list %}
      <ul>
        {% for author in author_list %}
           <li>
               <a href="{{ author.get_absolute_url }}"> 
                  {{ author.first_name }} {{ author.last_name }}
               </a>
           </li>
        {% endfor %}
      </ul>
    {% else %}
       <p>There are no authors in the library.</p>
    {% endif %}
{% endblock %}

PSW-Library-2025/library/catalog/templates/catalog/book_detail.html
{% extends "base_generic.html" %}

{% block content %}
   <h1>Title: {{ book.title }}</h1>
   <p><strong> Author:</strong> <a href="{{ book.author.get_absolute_url }}"> {{ book.author }}</a></p>
   <p><strong> Summary: </strong> {{ book.summary }}</p>
   <p><strong> ISBN: </strong> {{ book.isbn }}</p>
   <p><strong> Language: </strong> {{ book.language }}</p>
   <p><strong> Genre: </strong> {{ book.genre }}</p>
   
   <div style="margin-left:20px;margin-top:20px">
        {% if book.bookinstance_set.all %}
          <h4>Copies</h4>
          {% for copy in book.bookinstance_set.all %}
             <hr>
             <p id="para-{{copy.id}}" class="{% if copy.status == 'a' %}text-success{% elif copy.is_overdue %}text-danger{% else %}text-warning{% endif %}">
                {{ copy.get_status_display }}
                {% if perms.catalog.can_mark_returned %}
                   {% if copy.status == 'a' %}
                       <span id="span-{{copy.id}}">
                         <button onclick="setOnMaintenance('{{ copy.id }}')">
                               Put on maintenance
                         </button>
                       </span>
                   {% endif %}
                {% endif %}                
             </p>
             {% if copy.status == 'o' %}
                <p><strong>Due back by </strong> {{ copy.due_back }}</p>
             {% endif %}
             <p><strong>Imprint:</strong> {{ copy.imprint }}</p>
             <p class="text-muted"><strong>Id:</strong> {{ copy.id }}</p>
          {% endfor %}
        {% else %}
           <h4 class="text-danger">This book has no copies</h4>
        {% endif %}
</div>
   
   
{% endblock %}

PSW-Library-2025/library/catalog/templates/catalog/book_list.html
{% extends "base_generic.html" %}

{% block content %}
   <h1>Book List</h1>
   {% if book_list %}
      <ul>
        {% for book in book_list %}
           <li>
              <a href="{{ book.get_absolute_url }}"> {{ book.title }} </a>
              ({{book.author}})
           </li>
        {% endfor %}
      </ul>
   {% else %}
      <p>There are no books in the library.</p>
   {% endif %}
{% endblock %}

PSW-Library-2025/library/catalog/templates/catalog/book_renew_librarian.html
{% extends "base_generic.html" %}
{% block content %}

<h1>Renew: {{ book_instance.book.title }}</h1>
<p> Borrower: {{ book_instance.borrower }}</p>
<p{% if book_instance.is_overdue %} class="text-danger"{% endif %}>
  Due date: {{ book_instance.due_back }}
</p>

<form action="" method="post">
   {% csrf_token %}
   <table>
     {{ form.as_table }}
   </table>
   <input type="submit" value="Submit">
</form>
{% endblock %}

PSW-Library-2025/library/catalog/templates/catalog/bookinstance_list_loaned.html
{% extends "base_generic.html" %}

{% block content %}
   <h1>Borrowed books</h1>
   {% if bookinstance_list %}
      <ul>
         {% for b in bookinstance_list %}
            <li {% if b.is_overdue %} class="text-danger"{% endif %} >
               <a href="{% url 'book-detail' b.book.pk %}"> {{ b.book.title }} </a> ({{ b.due_back }})
               {% if perms.catalog.can_mark_returned %}
                  <a href="{% url 'renew-book-librarian' b.id %}">Renew</a>
               {% endif %}
            </li>
        {% endfor %}
     </ul>
  {% else %}
      <p>There are no books being borrowed.</p>
  {% endif %}
{% endblock %}

PSW-Library-2025/library/catalog/templates/catalog/search_book_librarian.html
{% extends "base_generic.html" %}

{% block content %}
   <h1>Search by book title:</h1>
   <form action="" method="post">
      {% csrf_token %}
      <table>
        {{ form.as_table }}
      </table>
      <input type="submit" value="Submit">
   </form>
{% endblock %}

PSW-Library-2025/library/catalog/templates/catalog/searched_book_librarian.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Search results for this title: '{{ search_title }}'</h1>
  <br> <br>

  {% for book in found_books %}
     <hr>
       <p> 
         <a href="{{ book.get_absolute_url }}"> {{ book.title }}</a> 
         ({{book.author}})
       </p>
     <hr>
   {% empty %}
     <h2 class="text-warning"> No book was found </h2>
   {% endfor %}
{% endblock %}

PSW-Library-2025/library/catalog/templates/catalog/signup.html
{% extends "base_generic.html" %}

{% block content %}
   <h1>Signup</h1>
   <form method="POST">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit">Signup</button>
   </form>
{% endblock %}